# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksign: false
    zipalign: false
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '9a1ba8cd-871a-4b78-a43f-fc4578180fe8'
    pipeline: '3'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    tags: 'apk'
    downloadType: 'single'
    artifactName: 'apk'
    itemPattern: '**/*.apk'
    downloadPath: '$(System.ArtifactsDirectory)'